### ISSUE TITLE
Is it possible to create a condensed version of emacs?

### ISSUE THREAD

**Issue by kekeimiku** [dickmao/commercial-emacs#77]
For example, separate leim org-mode and the like, and users can choose to install.

**Comment by dickmao** [comment]
TLDR; that's low hanging but bland tasting fruit.

While the diskspace footprint of emacs is about an order of magnitude
greater than it should be, bygone are the days when people understood
virtual memory, much less cared about it.  These days the savvier
"kids" explicitly set the swap partition to zero.

Let emacs, the twentieth century's poster child for bloatware [1],
accrete with abandon -- its disk consumption is peanuts in the age of
Docker.

[1] So much so that its X desktop icon was a (poorly rendered)
kitchen sink.
